databases:
  - name: benmifaarwanda-db
    plan: free
    databaseName: benmifa
    user: benmifa

services:
  - type: web
    name: benmifaarwanda
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn benmifaarwanda.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: benmifaarwanda-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
